// <auto-generated />
using System;
using Felfel.Inventory.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Felfel.Inventory.Entities.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20200629204041_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Felfel.Inventory.Entities.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliveredQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierName")
                        .HasColumnType("TEXT");

                    b.HasKey("BatchId");

                    b.ToTable("Batchs");

                    b.HasData(
                        new
                        {
                            BatchId = 1,
                            CreatedAt = new DateTime(2020, 6, 23, 1, 44, 46, 967, DateTimeKind.Local).AddTicks(9937),
                            CurrentQuantity = 50,
                            DeliveredQuantity = 50,
                            ExpirationDate = new DateTime(2020, 7, 4, 22, 40, 40, 966, DateTimeKind.Local).AddTicks(1812),
                            IsDeleted = false,
                            ProductId = 1,
                            SupplierName = "Mama Pasta"
                        },
                        new
                        {
                            BatchId = 2,
                            CreatedAt = new DateTime(2020, 6, 23, 1, 44, 46, 968, DateTimeKind.Local).AddTicks(662),
                            CurrentQuantity = 100,
                            DeliveredQuantity = 100,
                            ExpirationDate = new DateTime(2020, 7, 2, 22, 40, 40, 968, DateTimeKind.Local).AddTicks(515),
                            IsDeleted = false,
                            ProductId = 1,
                            SupplierName = "Mama Pasta"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
